---
title: "plotly"
author: "Gunnar"
date: "10/28/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

loading airbnb data

```{r}
library(tidyverse)
library(janitor)
library(p8105.datasets)
library(plotly)
```


cleaning the dataset
```{r}
data("nyc_airbnb")

airbnb <- nyc_airbnb  %>%
  rename(borough = neighbourhood_group) %>%
  mutate(rating = review_scores_location/2) %>%
  select(borough, neighbourhood, rating, price, room_type, lat, long) %>%
  filter(
    borough == "Manhattan", price %in% 100:500,
    room_type == "Entire home/apt"
  ) %>% drop_na(rating)
```




#time to make some plotly plots
##scaterplot

```{r}
airbnb %>%
  mutate(text_label = str_c("Price: $", price, "\nRating: ", rating)) %>%
  plot_ly(
    x = ~lat, y = ~long, color = ~price, text = ~text_label,
    alpha = .5, type = "scatter", mode = "markers", colors = "viridis"
  )
```





##boxplot

```{r}
airbnb %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, price)) %>%
  plot_ly(y = ~price, x = ~neighbourhood, color = ~neighbourhood,
          type = "box", colors = "viridis")
```


##bar plot
```{r}
airbnb %>%
  count(neighbourhood) %>%
  mutate(neighbourhood = fct_reorder(neighbourhood, n)) %>%
  plot_ly(x = ~neighbourhood, y = ~n, color = ~neighbourhood, 
          type = "bar", colors = "viridis")
```


##ggplotly
```{r}
airbnb_scatter <- airbnb %>%
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point()

ggplotly(airbnb_scatter)
```


#Dashboard time

